# DO NOT EDIT THIS FILE : It's generated from ./docker-bake.hcl.j2
group "default" {
   targets = [
     "8_0", "8_1", 
   ]
}
group "all" {
   targets = [
     "7_4", "8_0", "8_1", 
   ]
}

group "7_4" {
   targets = [
        "7_4-cli", "7_4-cli-dev",
        "7_4-apache", "7_4-apache-dev",
        "7_4-fpm", "7_4-fpm-dev",
   ]
}

group "8_0" {
   targets = [
        "8_0-cli", "8_0-cli-dev",
        "8_0-apache", "8_0-apache-dev",
        "8_0-fpm", "8_0-fpm-dev",
   ]
}

group "8_1" {
   targets = [
        "8_1-cli", "8_1-cli-dev",
        "8_1-apache", "8_1-apache-dev",
        "8_1-fpm", "8_1-fpm-dev",
   ]
}



variable "REPO" {default = "thecodingmachine/php"}
variable "TAG_PREFIX" {default = ""}
variable "PHP_PATCH_MINOR" {default = ""}
variable "IS_RELEASE" {default = "0"}

function "tag" {
    params = [PHP_VERSION, VARIANT]
    result = [
      equal("1",IS_RELEASE) ? "${REPO}:${PHP_VERSION}-v5-${VARIANT}" : "",
      equal("1",IS_RELEASE) ? (notequal("",PHP_PATCH_MINOR) ? "${REPO}:${PHP_PATCH_MINOR}-v5-${VARIANT}": "") : "",
      "${REPO}:${TAG_PREFIX}${PHP_VERSION}-v5-${VARIANT}",
    ]
}

target "default" {
  context = "."
  args = {
    GLOBAL_VERSION = "v5"
  }
  #platforms = ["linux/amd64", "linux/arm64"]
  #platforms = ["linux/amd64"]
  platforms = [BAKE_LOCAL_PLATFORM] # export in system platform by default
  pull = true
  output = ["type=docker"] # export in local docker by default
}



###############################
## PHP 7.4
###############################
# -------------------------------
# PHP 7.4 - variant cli
# -------------------------------
group "7_4-cli-all" {
   targets = [
        "7_4-cli", "7_4-cli-dev",
   ]
}
target "7_4-cli" {
  inherits = ["default"]
  tags = tag("7.4", "cli")
  dockerfile = "Dockerfile.7.4-cli"
  args = {
    PHP_VERSION_MINOR = "7.4"
    VARIANT = "cli"
  }
}
target "7_4-cli-dev" {
  inherits = ["7_4-cli"]
  tags = tag("7.4", "cli-dev")
  dockerfile = "Dockerfile.7.4-cli-dev"
  args = {
    PHP_VERSION_MINOR = "7.4"
    VARIANT = "cli"
    FROM_IMAGE = "regular"
  }
  contexts = {
    regular = "target:7_4-cli"
  }
}
# -------------------------------
# PHP 7.4 - variant apache
# -------------------------------
group "7_4-apache-all" {
   targets = [
        "7_4-apache", "7_4-apache-dev",
   ]
}
target "7_4-apache" {
  inherits = ["default"]
  tags = tag("7.4", "apache")
  dockerfile = "Dockerfile.7.4-apache"
  args = {
    PHP_VERSION_MINOR = "7.4"
    VARIANT = "apache"
  }
}
target "7_4-apache-dev" {
  inherits = ["7_4-apache"]
  tags = tag("7.4", "apache-dev")
  dockerfile = "Dockerfile.7.4-apache-dev"
  args = {
    PHP_VERSION_MINOR = "7.4"
    VARIANT = "apache"
    FROM_IMAGE = "regular"
  }
  contexts = {
    regular = "target:7_4-apache"
  }
}
# -------------------------------
# PHP 7.4 - variant fpm
# -------------------------------
group "7_4-fpm-all" {
   targets = [
        "7_4-fpm", "7_4-fpm-dev",
   ]
}
target "7_4-fpm" {
  inherits = ["default"]
  tags = tag("7.4", "fpm")
  dockerfile = "Dockerfile.7.4-fpm"
  args = {
    PHP_VERSION_MINOR = "7.4"
    VARIANT = "fpm"
  }
}
target "7_4-fpm-dev" {
  inherits = ["7_4-fpm"]
  tags = tag("7.4", "fpm-dev")
  dockerfile = "Dockerfile.7.4-fpm-dev"
  args = {
    PHP_VERSION_MINOR = "7.4"
    VARIANT = "fpm"
    FROM_IMAGE = "regular"
  }
  contexts = {
    regular = "target:7_4-fpm"
  }
}

###############################
## PHP 8.0
###############################
# -------------------------------
# PHP 8.0 - variant cli
# -------------------------------
group "8_0-cli-all" {
   targets = [
        "8_0-cli", "8_0-cli-dev",
   ]
}
target "8_0-cli" {
  inherits = ["default"]
  tags = tag("8.0", "cli")
  dockerfile = "Dockerfile.8.0-cli"
  args = {
    PHP_VERSION_MINOR = "8.0"
    VARIANT = "cli"
  }
}
target "8_0-cli-dev" {
  inherits = ["8_0-cli"]
  tags = tag("8.0", "cli-dev")
  dockerfile = "Dockerfile.8.0-cli-dev"
  args = {
    PHP_VERSION_MINOR = "8.0"
    VARIANT = "cli"
    FROM_IMAGE = "regular"
  }
  contexts = {
    regular = "target:8_0-cli"
  }
}
# -------------------------------
# PHP 8.0 - variant apache
# -------------------------------
group "8_0-apache-all" {
   targets = [
        "8_0-apache", "8_0-apache-dev",
   ]
}
target "8_0-apache" {
  inherits = ["default"]
  tags = tag("8.0", "apache")
  dockerfile = "Dockerfile.8.0-apache"
  args = {
    PHP_VERSION_MINOR = "8.0"
    VARIANT = "apache"
  }
}
target "8_0-apache-dev" {
  inherits = ["8_0-apache"]
  tags = tag("8.0", "apache-dev")
  dockerfile = "Dockerfile.8.0-apache-dev"
  args = {
    PHP_VERSION_MINOR = "8.0"
    VARIANT = "apache"
    FROM_IMAGE = "regular"
  }
  contexts = {
    regular = "target:8_0-apache"
  }
}
# -------------------------------
# PHP 8.0 - variant fpm
# -------------------------------
group "8_0-fpm-all" {
   targets = [
        "8_0-fpm", "8_0-fpm-dev",
   ]
}
target "8_0-fpm" {
  inherits = ["default"]
  tags = tag("8.0", "fpm")
  dockerfile = "Dockerfile.8.0-fpm"
  args = {
    PHP_VERSION_MINOR = "8.0"
    VARIANT = "fpm"
  }
}
target "8_0-fpm-dev" {
  inherits = ["8_0-fpm"]
  tags = tag("8.0", "fpm-dev")
  dockerfile = "Dockerfile.8.0-fpm-dev"
  args = {
    PHP_VERSION_MINOR = "8.0"
    VARIANT = "fpm"
    FROM_IMAGE = "regular"
  }
  contexts = {
    regular = "target:8_0-fpm"
  }
}

###############################
## PHP 8.1
###############################
# -------------------------------
# PHP 8.1 - variant cli
# -------------------------------
group "8_1-cli-all" {
   targets = [
        "8_1-cli", "8_1-cli-dev",
   ]
}
target "8_1-cli" {
  inherits = ["default"]
  tags = tag("8.1", "cli")
  dockerfile = "Dockerfile.8.1-cli"
  args = {
    PHP_VERSION_MINOR = "8.1"
    VARIANT = "cli"
  }
}
target "8_1-cli-dev" {
  inherits = ["8_1-cli"]
  tags = tag("8.1", "cli-dev")
  dockerfile = "Dockerfile.8.1-cli-dev"
  args = {
    PHP_VERSION_MINOR = "8.1"
    VARIANT = "cli"
    FROM_IMAGE = "regular"
  }
  contexts = {
    regular = "target:8_1-cli"
  }
}
# -------------------------------
# PHP 8.1 - variant apache
# -------------------------------
group "8_1-apache-all" {
   targets = [
        "8_1-apache", "8_1-apache-dev",
   ]
}
target "8_1-apache" {
  inherits = ["default"]
  tags = tag("8.1", "apache")
  dockerfile = "Dockerfile.8.1-apache"
  args = {
    PHP_VERSION_MINOR = "8.1"
    VARIANT = "apache"
  }
}
target "8_1-apache-dev" {
  inherits = ["8_1-apache"]
  tags = tag("8.1", "apache-dev")
  dockerfile = "Dockerfile.8.1-apache-dev"
  args = {
    PHP_VERSION_MINOR = "8.1"
    VARIANT = "apache"
    FROM_IMAGE = "regular"
  }
  contexts = {
    regular = "target:8_1-apache"
  }
}
# -------------------------------
# PHP 8.1 - variant fpm
# -------------------------------
group "8_1-fpm-all" {
   targets = [
        "8_1-fpm", "8_1-fpm-dev",
   ]
}
target "8_1-fpm" {
  inherits = ["default"]
  tags = tag("8.1", "fpm")
  dockerfile = "Dockerfile.8.1-fpm"
  args = {
    PHP_VERSION_MINOR = "8.1"
    VARIANT = "fpm"
  }
}
target "8_1-fpm-dev" {
  inherits = ["8_1-fpm"]
  tags = tag("8.1", "fpm-dev")
  dockerfile = "Dockerfile.8.1-fpm-dev"
  args = {
    PHP_VERSION_MINOR = "8.1"
    VARIANT = "fpm"
    FROM_IMAGE = "regular"
  }
  contexts = {
    regular = "target:8_1-fpm"
  }
}
