ARG INSTALL_CRON=1
ARG INSTALL_COMPOSER=1
FROM thecodingmachine/php:7.2-v2-slim-apache

LABEL authors="Julien Neuhart <j.neuhart@thecodingmachine.com>, David Négrier <d.negrier@thecodingmachine.com>"


# |--------------------------------------------------------------------------
# | Main PHP extensions
# |--------------------------------------------------------------------------
# |
# | Installs the main PHP extensions
# |

USER root
RUN cd /usr/local/lib/thecodingmachine-php/extensions/current/ && ./install_all.sh && ./disable_all.sh
USER docker

# |--------------------------------------------------------------------------
# | Default PHP extensions to be enabled (in addition to the one declared in Slim build)
# |--------------------------------------------------------------------------
ENV PHP_EXTENSION_APCU=1 \
    PHP_EXTENSION_MYSQLI=1 \
    PHP_EXTENSION_PDO_MYSQL=1 \
    PHP_EXTENSION_IGBINARY=1 \
    PHP_EXTENSION_REDIS=1 \
    PHP_EXTENSION_SOAP=1


