blueprint: ## Generate all blueprints file
	@if ! type orbit >/dev/null 2>&1; then echo "Missing orbit dependency, please install from https://github.com/gulien/orbit/"; exit 1; fi
	orbit run generate
	@sed -i '1i\# DO NOT EDIT THIS FILE : Make yours changes in /utils/Dockerfile.*.blueprint)' Dockerfile.*
	@sed -i '1i\[DO NOT EDIT THIS FILE]: <> (Make yours changes in /utils/README.blueprint.md)' README.md

test-latest: blueprint ## Test the latest build only
	(PHP_VERSION=7.4 BRANCH=v4 VARIANT=apache ./build-and-test.sh && notify-send -u critical "Tests passed with success") || notify-send -u critical "Tests failed"

clean: ## Clean dangles image after build
