name: Docker PHP Images GitHub workflow

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test compilation of blueprints files
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Regenerate blueprint
        run: make blueprint-all
      - name: Check if something changed
        run: |
          if [[ "$(git diff --name-only -w | wc -l)" -ne "0" ]]; then
            echo "Wrong file generation are theses one :"
            git diff -U0 -w
            exit 1
          fi
          echo "It's fine !"